extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_Grass_lights;
extern Lights1 castle_grounds_dl_Sand_lights;
extern Lights1 castle_grounds_dl_Rock_lights;
extern Lights1 castle_grounds_dl_Wood_lights;
extern Lights1 castle_grounds_dl_Water_lights;
extern u8 castle_grounds_dl_grass_ci8[];
extern u8 castle_grounds_dl_grass_pal_rgba16[];
extern u8 castle_grounds_dl_sand_ci8[];
extern u8 castle_grounds_dl_sand_pal_rgba16[];
extern u8 castle_grounds_dl_rock_ci8[];
extern u8 castle_grounds_dl_rock_pal_rgba16[];
extern u8 castle_grounds_dl_wood_ci8[];
extern u8 castle_grounds_dl_wood_pal_rgba16[];
extern u8 castle_grounds_dl_water_ci8[];
extern u8 castle_grounds_dl_water_pal_rgba16[];
extern Vtx castle_grounds_dl_MainIsland_mesh_layer_1_vtx_0[922];
extern Gfx castle_grounds_dl_MainIsland_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_MainIsland_mesh_layer_1_vtx_1[1676];
extern Gfx castle_grounds_dl_MainIsland_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_MainIsland_mesh_layer_1_vtx_2[137];
extern Gfx castle_grounds_dl_MainIsland_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_MainIsland_mesh_layer_1_vtx_3[57];
extern Gfx castle_grounds_dl_MainIsland_mesh_layer_1_tri_3[];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Gfx mat_castle_grounds_dl_Grass[];
extern Gfx mat_revert_castle_grounds_dl_Grass[];
extern Gfx mat_castle_grounds_dl_Sand[];
extern Gfx mat_revert_castle_grounds_dl_Sand[];
extern Gfx mat_castle_grounds_dl_Rock[];
extern Gfx mat_revert_castle_grounds_dl_Rock[];
extern Gfx mat_castle_grounds_dl_Wood[];
extern Gfx mat_revert_castle_grounds_dl_Wood[];
extern Gfx mat_castle_grounds_dl_Water[];
extern Gfx mat_revert_castle_grounds_dl_Water[];
extern Gfx castle_grounds_dl_MainIsland_mesh_layer_1[];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
