extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_Grass_lights;
extern Lights1 castle_grounds_dl_sm64_water_mat_lights;
extern u8 castle_grounds_dl_grass_ci8[];
extern u8 castle_grounds_dl_grass_pal_rgba16[];
extern u8 castle_grounds_dl_water_ci8[];
extern u8 castle_grounds_dl_water_pal_rgba16[];
extern Vtx castle_grounds_dl_Main_mesh_layer_1_vtx_0[3343];
extern Gfx castle_grounds_dl_Main_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Gfx mat_castle_grounds_dl_Grass[];
extern Gfx mat_revert_castle_grounds_dl_Grass[];
extern Gfx mat_castle_grounds_dl_sm64_water_mat[];
extern Gfx mat_revert_castle_grounds_dl_sm64_water_mat[];
extern Gfx castle_grounds_dl_Main_mesh_layer_1[];
extern Gfx castle_grounds_dl_Water_Box_Mesh_mesh_layer_5[];
