#include "src/game/envfx_snow.h"

const GeoLayout jellyfish_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SCALE(LAYER_OPAQUE, 16384),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, jellyfish_Main_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jellyfish_Main_mesh_layer_5),
				GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleA1_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 2, -119, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, jellyfish_tentacleA1_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleB1_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 250, 0, jellyfish_tentacleB1_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleC1_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 271, 0, jellyfish_tentacleC1_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleA2_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 113, 2, -37, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, jellyfish_tentacleA2_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleB2_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 250, 0, jellyfish_tentacleB2_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleC2_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 271, 0, jellyfish_tentacleC2_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleA3_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 70, 2, 96, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, jellyfish_tentacleA3_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleB3_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 250, 0, jellyfish_tentacleB3_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleC3_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 271, 0, jellyfish_tentacleC3_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleA4_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -70, 2, 96, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, jellyfish_tentacleA4_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleB4_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 250, 0, jellyfish_tentacleB4_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleC4_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 271, 0, jellyfish_tentacleC4_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleA5_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -113, 2, -37, 180, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, jellyfish_tentacleA5_mesh_layer_4),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleB5_skinned_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 250, 0, jellyfish_tentacleB5_mesh_layer_4),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_tentacleC5_skinned_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_ALPHA, 0, 271, 0, jellyfish_tentacleC5_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, jellyfish_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, jellyfish_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, jellyfish_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
